# Generated by Django 3.1.3 on 2020-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('pizza_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('pizza_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('pizza_price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
            ],
        ),
    ]
